In [1]:
# from clickhouse_driver import Client

# client = Client(host='localhost', password='c6n3s2')

# print(client.execute('SHOW DATABASES'))

# print(client.execute('SELECT * FROM system.numbers LIMIT 5'))

from clickhouse_driver import Client
from datetime import datetime
import json

def validate(jsonData):
	missing_fields = []
	is_valid = False
	mandatory_fields = ['time', 'type', 'correlation_id', 'site_id']
	try:
		data = json.loads(jsonData)

		print(data)
		for field in mandatory_fields:
			try:
				value = data[field]
				print(f'Mandatory field {field} here!')
			except:
				print(f'Mandatory field {field} not here!')
				missing_fields.append(field)
		if not missing_fields:
			is_valid = True
			return is_valid, missing_fields
	except:
		print('Not a json format!')
		return is_valid, missing_fields

def insert(jsonData):
	isValidSchema, missing_fields = validate(jsonData)
	print(isValidSchema)
	if isValidSchema:
		data = json.loads(jsonData)
		types = "'{}'".format(data['type'])
		correlation_id = "'{}'".format(data['correlation_id'])
		site_id = "'{}'".format(data['site_id'])
		dt = "'{}'".format(datetime.fromisoformat(data['time']).strftime("%Y-%m-%dT00:00:00"))
		
		insert_query = "INSERT INTO test.real_test_6 (*) VALUES ({}, {}, {}, {})".format(dt, types, correlation_id, site_id)

		print(insert_query)
		client = Client(host='localhost', password='c6n3s2'
		)
		client.execute('CREATE TABLE IF NOT EXISTS test.real_test_6 ( ''time'' String, ''type'' String, ''correlation_id'' String, ''site_id'' String) ENGINE = MergeTree() ORDER BY time')
		client.execute(insert_query)
		value = '{"time": "2021-01-22T18:20:42.159246", "type": "serve", "correlation_id": "357d1bc4-3502-4592-8355-874b1c31f1a6", "site_id": "0faf8b64-a33d-4db8-aaee-aa165d13cff6"}'
	else:
		value = 'kkkkk'
	return value

In [6]:
from clickhouse_driver import Client
def read():
    client = Client(host='localhost', password='c6n3s2')
    banana = client.execute("select distinct time, site_id, type, count(distinct correlation_id) as records from test.real_test_6 group by time, site_id, type;")
    print('####################################################')
    return banana

In [20]:
import pandas as pd
import json
js = {}
a = read()
df = pd.DataFrame(a, columns=['time', 'site_id','type', 'events'])
df
# for j in a:
#     for k in j:
#         print(k)
#         print("#################")

####################################################

                   time                               site_id    type  events
0   2021-01-11T00:00:00    0fab64-a33d-4db8-aaee-aa165d13cff6   serve       1
1   2021-01-27T00:00:00  0faf8b64-a33d-4db8-aaee-aa165d13cff6   serve       1
2   2021-01-27T00:00:00  0faf8b64-a33d-4db8-aaee-aa165d13cff6  solved       1
3   2021-01-22T00:00:00        0faf8b64-a33d-4db8-aaee-aa1656   serve       1
4   2021-01-11T00:00:00       0f4-a33d-4db8-aaee-aa165d13cff6   serve       1
5   2021-01-22T00:00:00  0faf8b64-a33d-4db8-aaee-aa165d13cff6  solved       3
6   2021-01-22T00:00:00  0faf8b64-a33d-4db8-aaee-aa165d13cff6   serve       1
7   2021-01-22T00:00:00    0faf8b64-a33d-4db8-aae-a165d13cff6   serve       1
8   2021-01-22T00:00:00    0faf64-a33d-4db8-aaee-aa165d13cff6   serve       1
9   2021-01-21T00:00:00    0faf8b64-a33d-4db8-aaee-a65d13cff6   serve       1
10  2021-01-13T00:00:00  0faf8b64-a33d-4db8-aaee-aa165d13cff6  solved       1
11  2021-01-21T00:00:00  0faf8b64-a33d-4db8-aaee-aa165d13cff6   serve       1
12  2021-01-24T00:00:00  0faf8b64-a33d-4db8-aaee-aa165d13cff6   serve       1

In [34]:
d = df.to_dict(orient='records')
flx = {}
for item in d:
    if item['type'] == 'serve': 
        column = 'serve'
    else:
        column = 'solved'
    js = {
        'time': item['time'],
        'site_id': item['site_id'],
        column: item['type'],
        'events': item['events']
    }
    flx.update(js)
flx

{'time': '2021-01-24T00:00:00',
 'sitte_id': '0faf8b64-a33d-4db8-aaee-aa165d13cff6',
 'serve': 'serve',
 'events': 1,
 'solved': 'solved'}